[[stack]]
name = "oklabwebprod_oklab-web"
[stack.config]
server = "oklabwebtest"
linked_repo = "int-gitops"
file_paths = [
    "apps/compose.yml",
    "apps/oklab-web/compose.yml",
    "apps/oklab-web/compose.oklabwebtest.yml"
]
pre_deploy.command = """
  chmod 777 ./scripts/env-decryption.sh
  ./scripts/env-decryption.sh oklab-web oklabwebtest
"""
pre_deploy.shell_mode = false
extra_args = ["--force-recreate"]