[[stack]]
name = "int-zkouska"
[stack.config]
server = "int"
linked_repo = "int-gitops"
file_paths = [
    "apps/compose.yml",
    "apps/example-application-1/compose.yml",
    "apps/example-application-1/compose.int.yml"
]
pre_deploy.command = """
  chmod 777 ./scripts/env-decryption.sh
  ./scripts/env-decryption.sh example-application-1 int
"""
pre_deploy.shell_mode = false
extra_args = ["--force-recreate"]