[[stack]]
name = "int_example-application-2"
[stack.config]
server = "int"
linked_repo = "int-gitops"
file_paths = [
    "apps/compose.yml",
    "apps/example-application-2/compose.yml",
]
pre_deploy.command = """
  chmod 777 ./scripts/env-decryption.sh
  ./scripts/env-decryption.sh example-application-2
"""
pre_deploy.shell_mode = false
extra_args = ["--force-recreate"]
