services:
  web:
    container_name: test-web-1
    image: nginx:alpine
    restart: unless-stopped
    labels:
      env_enc_hash_main: "2478afc2edc9f6f99b8a43d67365b7bb"
    env_file:
      - ../../envs/example-application-2.env