services:
  web:
    container_name: test-web-1
    image: nginx:alpine
    restart: always
    labels:
      env_enc_hash_main: "55bb85e7ba7e78657323dbdb3d4f2436"
    env_file:
      - example-application-1/.env