services:
  web:
    container_name: web-alfa-test-test-test
    image: docker.io/library/nginx:trixie-perl
    labels:
      env_enc_hash: "1d1407d2660d17c19390c9ce563812aa"
    env_file:
      - example-application-1/.int.env
      #- /etc/.enc.env
      # - /etc/.prod.env
