services:
  web:
    container_name: web-alfa-test-test-test
    image: docker.io/library/nginx:trixie-perl
    labels:
      env_enc_hash: "2d5961fb30d92bc912247f742648ae9b"
    env_file:
      - ../../envs/int/example-application-1.env
      #- /etc/.enc.env
      # - /etc/.prod.env
