services:
  web:
    container_name: web-alfa-test-test-test
    image: docker.io/library/nginx:trixie-perl
    labels:
      env_enc_hash: "1e1952ddbb80d1c45ee25008783c1c54"
    env_file:
      - ../../envs/int/example-application-1.env
      #- /etc/.enc.env
      # - /etc/.prod.env
