x-podman:
  docker_compose_compat: true

services:
  web:
    container_name: test-web-1
    image: nginx:alpine
    restart: unless-stopped
    labels:
      env_enc_hash: "3b2b9eda9cc90d76fb266fc087512e4c"
    env_file:
      - ../../envs/example-application-1.env  #bere to z /home/vyhnalek/komodo/repos/repo-1 - takže i když se ten compose pouští v /home/vyhnalek/komodo/repos, tak
    #  - server-beta/.env