[[stack]]
name = "repo1-int"
[stack.config]
server = "int"
files_on_host = true
run_directory = "/home/vyhnalek/komodo/repos"
file_paths = [
    "repo-1/docker-compose.yaml",
    "repo-1/int/docker-compose.override.yaml"
]