x-podman:
  docker_compose_compat: true

services:
  web:
    container_name: test-web-1
    image: nginx:alpine
    restart: unless-stopped
    env_file:
      - .env  #bere to z /home/vyhnalek/komodo/repos/repo-1 - takže i když se ten compose pouští v /home/vyhnalek/komodo/repos, tak
    #  - server-beta/.env